import { test, expect } from '@playwright/test';
import { getAdminNonce } from '../../utils/factories';

test.use({ storageState: 'e2e/.auth/admin.json' });

/**
 * Per-addon documentation deep-link smoke.
 *
 * Anchors are auto-generated by the docs site from h3 headings, and the
 * heading slugs do NOT match the plugin's internal addon IDs verbatim
 * (e.g. `coupons_advanced` → `#advanced-coupons-upsells`). This spec
 * pins a representative sample so any future drift between
 * `AdminAddonsRestRoutes::docsUrlForAddon()` and the live docs structure
 * is caught immediately.
 */
test.describe('admin: per-addon documentation deep links', () => {
  test('GET /admin/addons returns Sikshya docs URLs with the correct anchors', async ({
    page,
    request,
  }) => {
    const nonce = await getAdminNonce(page);
    const res = await request.get('/wp-json/sikshya/v1/admin/addons', {
      headers: { 'X-WP-Nonce': nonce },
    });
    const body = await res.json().catch(() => ({}));
    expect(res.ok(), JSON.stringify(body).slice(0, 200)).toBeTruthy();
    expect(Array.isArray(body?.addons)).toBe(true);

    const byId: Record<string, { docsUrl?: string }> = Object.fromEntries(
      (body.addons as Array<{ id: string; docsUrl?: string }>).map((a) => [a.id, a]),
    );

    // Representative sample — addons whose docs slug is *not* a naive
    // `id.replace('_', '-')` of the ID. These would have broken under the
    // earlier slugify-based implementation.
    const expectedAnchors: Record<string, string> = {
      coupons_advanced: 'third-party-integrations/#advanced-coupons-upsells',
      course_reviews: 'third-party-integrations/#course-reviews-ratings',
      community_discussions: 'third-party-integrations/#course-discussions-qa',
      multi_instructor: 'third-party-integrations/#multi-instructor-co-authors',
      live_classes: 'third-party-integrations/#live-classes-zoom-meet-classroom',
      scorm_h5p_pro: 'third-party-integrations/#scorm-h5p',
      content_drip: 'third-party-integrations/#content-drip-scheduled-unlock',
      drip_notifications: 'third-party-integrations/#drip-automation-emails',
      prerequisites: 'third-party-integrations/#prerequisites-lessons-courses',
      assignments_advanced: 'third-party-integrations/#advanced-assignments',
      quiz_advanced: 'third-party-integrations/#advanced-quiz-types-question-banks',
      certificates_advanced:
        'third-party-integrations/#advanced-certificates-builder-qr-verification',
      subscriptions: 'third-party-integrations/#subscriptions-memberships',
      reports_advanced: 'third-party-integrations/#advanced-analytics-exports',
      activity_log: 'third-party-integrations/#student-activity-log',
      enterprise_reports: 'third-party-integrations/#enterprise-reporting',
      email_marketing: 'third-party-integrations/#email-marketing-mailchimp-mailerlite',
      public_api_keys: 'third-party-integrations/#public-api-api-keys',
      marketplace_multivendor: 'third-party-integrations/#multi-vendor-marketplace',
      white_label: 'third-party-integrations/#white-label-branding',
      multisite_scale: 'third-party-integrations/#multisite-network-license-tools',
      multilingual_enterprise: 'third-party-integrations/#multilingual-wpml-weglot',
    };

    const base = 'https://sikshya.mantrabrain.com/docs/';
    const failures: string[] = [];
    for (const [id, suffix] of Object.entries(expectedAnchors)) {
      const row = byId[id];
      if (!row) {
        // Addon isn't registered in the current build (e.g. tier filter
        // changed) — skip it rather than failing the run.
        continue;
      }
      const expected = base + suffix;
      if (row.docsUrl !== expected) {
        failures.push(`${id}\n  got:      ${row.docsUrl}\n  expected: ${expected}`);
      }
    }
    expect(failures, `${failures.length} docs URL(s) drifted:\n${failures.join('\n\n')}`).toEqual([]);

    // Sanity: ALL serialized addons must have a docsUrl pointing at the
    // Sikshya docs site (no wp.org / mantrabrain.com fallbacks).
    const sansDocs = (body.addons as Array<{ id: string; docsUrl?: string }>).filter(
      (a) => !a.docsUrl || !/^https:\/\/sikshya\.mantrabrain\.com\/docs\//.test(a.docsUrl),
    );
    expect(sansDocs.map((a) => a.id), `addons without sikshya.mantrabrain.com docs URL`).toEqual([]);
  });
});
